### ISSUE TITLE
Infinite Scroll load more logic issue

### ISSUE THREAD

**Issue by armujahid** [armujahid/hnreact#45]
Loader should not be shown at the end of page
![image](https://user-images.githubusercontent.com/3725386/96030627-a957d400-0e75-11eb-990c-858fd740adee.png)

**Comment by tharindulucky** [comment]
@armujahid I'd like to work on this issue. 

When all the items are loaded, you want the "Loading..." label to be hidden. Right ?

**Comment by armujahid** [comment]
@tharindulucky thanks. Yes you can check stories.js file. hasMoreItems state should be false at the end of the page.

**Comment by tharindulucky** [comment]
@armujahid  I fixed the issue and added the PR #48 
You can review it now!
